knp_gaufrette:
    stream_wrapper: ~

    adapters:
        article_adapter:
            local:
                directory: "%kernel.project_dir%/public/images/articles"

    filesystems:
        article_fs:
            adapter: article_adapter

vich_uploader:
    db_driver: orm
    storage: gaufrette

    metadata:
        type: attribute

    mappings:
        articles:
            uri_prefix: /images/articles
            upload_destination: article_fs
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
